db = db.getSiblingDB('teg')
db.dropDatabase()
db.paises.insert([
  {
    id: 1,
    nombre: 'Alaska',
    archivo: 'ALASKA.png',
    posX: 27,
    posY: 49,
    continente: 3,
    escudo: 5,
  },
  {
    id: 2,
    nombre: 'Albania',
    archivo: 'ALBANIA.png',
    posX: 1046,
    posY: 428,
    continente: 6,
    escudo: 5,
  },
  {
    id: 3,
    nombre: 'Alemania',
    archivo: 'ALEMANIA.png',
    posX: 836,
    posY: 339,
    continente: 6,
    escudo: 5,
  },
  {
    id: 4,
    nombre: 'Angola',
    archivo: 'ANGOLA.png',
    posX: 1224,
    posY: 837,
    continente: 1,
    escudo: 5,
  },
  {
    id: 5,
    nombre: 'Arabia',
    archivo: 'ARABIA.png',
    posX: 1129,
    posY: 628,
    continente: 5,
    escudo: 5,
  },
  {
    id: 6,
    nombre: 'Argentina',
    archivo: 'ARGENTINA.png',
    posX: 293,
    posY: 954,
    continente: 4,
    escudo: 5,
  },

  {
    id: 7,
    nombre: 'Australia',
    archivo: 'AUSTRALIA.png',
    posX: 1224,
    posY: 837,
    continente: 7,
    escudo: 5,
  },
  {
    id: 8,
    nombre: 'Bielorrusia',
    archivo: 'BIELORRUSIA.png',
    posX: 981,
    posY: 152,
    continente: 6,
    escudo: 5,
  },
  {
    id: 9,
    nombre: 'Bolivia',
    archivo: 'BOLIVIA.png',
    posX: 260,
    posY: 866,
    continente: 4,
    escudo: 5,
  },
  {
    id: 10,
    nombre: 'Brasil',
    archivo: 'BRASIL.png',
    posX: 252,
    posY: 789,
    continente: 4,
    escudo: 5,
  },
  {
    id: 11,
    nombre: 'California',
    archivo: 'CALIFORNIA.png',
    posX: 58,
    posY: 398,
    continente: 3,
    escudo: 5,
  },
  {
    id: 12,
    nombre: 'Canada',
    archivo: 'CANADA.png',
    posX: 67,
    posY: 114,
    continente: 3,
    escudo: 5,
  },
  {
    id: 13,
    nombre: 'Colombia',
    archivo: 'COLOMBIA.png',
    posX: 176,
    posY: 691,
    continente: 4,
    escudo: 5,
  },
  {
    id: 14,
    nombre: 'Corea',
    archivo: 'COREA.png',
    posX: 1326,
    posY: 327,
    continente: 5,
    escudo: 5,
  },
  {
    id: 15,
    nombre: 'Croacia',
    archivo: 'CROACIA.png',
    posX: 916,
    posY: 490,
    continente: 6,
    escudo: 5,
  },
  {
    id: 16,
    nombre: 'Cuba',
    archivo: 'CUBA.png',
    posX: 321,
    posY: 480,
    continente: 2,
    escudo: 5,
  },
  {
    id: 17,
    nombre: 'Chechenia',
    archivo: 'CHECHENIA.png',
    posX: 1168,
    posY: 136,
    continente: 5,
    escudo: 5,
  },
  {
    id: 18,
    nombre: 'Chicago',
    archivo: 'CHICAGO.png',
    posX: 260,
    posY: 277,
    continente: 3,
    escudo: 5,
  },
  {
    id: 19,
    nombre: 'Chile',
    archivo: 'CHILE.png',
    posX: 208,
    posY: 818,
    continente: 4,
    escudo: 5,
  },
  {
    id: 20,
    nombre: 'China',
    archivo: 'CHINA.png',
    posX: 1231,
    posY: 29,
    continente: 5,
    escudo: 5,
  }, {
    id: 21,
    nombre: 'Chukchi',
    archivo: 'CHUKCHI.png',
    posX: 1294,
    posY: 54,
    continente: 5,
    escudo: 5,
  },
  {
    id: 22,
    nombre: 'Irlanda',
    archivo: 'IRLANDA.png',
    posX: 1224,
    posY: 837,
    continente: 6,
    escudo: 5,
  },
  {
    id: 23,
    nombre: 'Etiopia',
    archivo: 'ETIOPIA.png',
    posX: 1224,
    posY: 837,
    continente: 1,
    escudo: 5,
  },
  {
    id: 24,
    nombre: 'Egipto',
    archivo: 'EGIPTO.png',
    posX: 1224,
    posY: 837,
    continente: 1,
    escudo: 5,
  },
  {
    id: 25,
    nombre: 'El Salvador',
    archivo: 'EL_SALVADOR.png',
    posX: 269,
    posY: 580,
    continente: 2,
    escudo: 5,
  },
  {
    id: 26,
    nombre: 'España',
    archivo: 'ESPANA.png',
    posX: 700,
    posY: 543,
    continente: 6,
    escudo: 5,
  },
  {
    id: 27,
    nombre: 'Filipinas',
    archivo: 'FILIPINAS.png',
    posX: 1340,
    posY: 750,
    continente: 7,
    escudo: 5,
  },
  {
    id: 28,
    nombre: 'Finlandia',
    archivo: 'FINLANDIA.png',
    posX: 919,
    posY: 166,
    continente: 6,
    escudo: 5,
  },
  {
    id: 29,
    nombre: 'Francia',
    archivo: 'FRANCIA.png',
    posX: 1224,
    posY: 837,
    continente: 6,
    escudo: 5,
  },
  {
    id: 30,
    nombre: 'Gran Bretania',
    archivo: 'GRANBRETAÑA.png',
    posX: 1224,
    posY: 837,
    continente: 6,
    escudo: 5,
  },
  {
    id: 31,
    nombre: 'Greonlandia',
    archivo: 'GREONLANDIA.png',
    posX: 1224,
    posY: 837,
    continente: 6,
    escudo: 5,
  },
  {
    id: 32,
    nombre: 'Honduras',
    archivo: 'HONDURAS.png',
    posX: 1224,
    posY: 837,
    continente: 2,
    escudo: 5,
  },
  {
    id: 33,
    nombre: 'India',
    archivo: 'INDIA.png',
    posX: 1258,
    posY: 552,
    continente: 5,
    escudo: 5,
  },
  {
    id: 34,
    nombre: 'Irak',
    archivo: 'IRAK.png',
    posX: 1057,
    posY: 444,
    continente: 5,
    escudo: 5,
  },
  {
    id: 35,
    nombre: 'Iran',
    archivo: 'IRAN.png',
    posX: 1107,
    posY: 363,
    continente: 5,
    escudo: 5,
  },
  {
    id: 36,
    nombre: 'Islandia',
    archivo: 'ISLANDIA.png',
    posX: 1224,
    posY: 837,
    continente: 6,
    escudo: 5,
  },
  {
    id: 37,
    nombre: 'Isla Victoria ',
    archivo: 'ISLAVICTORIA.png',
    posX: 1224,
    posY: 837,
    continente: 3,
    escudo: 5,
  },
  {
    id: 38,
    nombre: 'Israel',
    archivo: 'ISRAEL.png',
    posX: 1089,
    posY: 529,
    continente: 5,
    escudo: 5,
  },
  {
    id: 39,
    nombre: 'Italia',
    archivo: 'ITALIA.png',
    posX: 1224,
    posY: 837,
    continente: 6,
    escudo: 5,
  },
  {
    id: 40,
    nombre: 'Jamaica',
    archivo: 'JAMAICA.png',
    posX: 1224,
    posY: 837,
    continente: 2,
    escudo: 5,
  },
  {
    id: 41,
    nombre: 'Japon',
    archivo: 'JAPON.png',
    posX: 1456,
    posY: 256,
    continente: 5,
    escudo: 5,
  },
  {
    id: 42,
    nombre: 'Kamchatka',
    archivo: 'KAMCHATKA.png',
    posX: 1306,
    posY: 106,
    continente: 5,
    escudo: 5,
  },
  {
    id: 43,
    nombre: 'Florida',
    archivo: 'FLORIDA.png',
    posX: 221,
    posY: 382,
    continente: 3,
    escudo: 5,
  },
  {
    id: 44,
    nombre: 'Labrador',
    archivo: 'LABRADOR.png',
    posX: 1224,
    posY: 837,
    continente: 3,
    escudo: 5,
  },
  {
    id: 45,
    nombre: 'Las Vegas',
    archivo: 'LASVEGAS.png',
    posX: 1224,
    posY: 837,
    continente: 3,
    escudo: 5,
  },
  {
    id: 46,
    nombre: 'Madagascar',
    archivo: 'MADAGASCAR.png',
    posX: 1224,
    posY: 837,
    continente: 1,
    escudo: 5,
  },
  {
    id: 47,
    nombre: 'Malasia',
    archivo: 'MALASIA.png',
    posX: 1272,
    posY: 455,
    continente: 5,
    escudo: 5,
  },
  {
    id: 48,
    nombre: 'Mauritania',
    archivo: 'MAURITANIA.png',
    posX: 1224,
    posY: 837,
    continente: 1,
    escudo: 5,
  },
  {
    id: 49,
    nombre: 'Mexico',
    archivo: 'MEXICO.png',
    posX: 1224,
    posY: 837,
    continente: 2,
    escudo: 5,
  },
  {
    id: 50,
    nombre: 'Nicaragua',
    archivo: 'NICARAGUA.png',
    posX: 1224,
    posY: 837,
    continente: 2,
    escudo: 5,
  },
  {
    id: 51,
    nombre: 'Nigeria',
    archivo: 'NIGERIA.png',
    posX: 1224,
    posY: 837,
    continente: 1,
    escudo: 5,
  },
  {
    id: 52,
    nombre: 'Noruega',
    archivo: 'NORUEGA.png',
    posX: 1224,
    posY: 837,
    continente: 6,
    escudo: 5,
  },
  {
    id: 53,
    nombre: 'Nueva York',
    archivo: 'NUEVAYORK.png',
    posX: 1224,
    posY: 837,
    continente: 3,
    escudo: 5,
  },
  {
    id: 54,
    nombre: 'Nueva Zelandia',
    archivo: 'NUEVA_ZELANDIA.png',
    posX: 1233,
    posY: 1074,
    continente: 8,
    escudo: 5,
  },
  {
    id: 55,
    nombre: 'Oregon',
    archivo: 'OREGON.png',
    posX: 1224,
    posY: 837,
    continente: 3,
    escudo: 5,
  },
  {
    id: 56,
    nombre: 'Paraguay',
    archivo: 'PARAGUAY.png',
    posX: 324,
    posY: 892,
    continente: 4,
    escudo: 5,
  },
  {
    id: 57,
    nombre: 'Ucrania',
    archivo: 'UCRANIA.png',
    posX: 1224,
    posY: 837,
    continente: 6,
    escudo: 5,
  },
  {
    id: 58,
    nombre: 'Portugal',
    archivo: 'PORTUGAL.png',
    posX: 1224,
    posY: 837,
    continente: 6,
    escudo: 5,
  },
  {
    id: 59,
    nombre: 'Rusia',
    archivo: 'RUSIA.png',
    posX: 1092,
    posY: 41,
    continente: 5,
    escudo: 5,
  },
  {
    id: 60,
    nombre: 'Sahara',
    archivo: 'SAHARA.png',
    posX: 1224,
    posY: 837,
    continente: 1,
    escudo: 5,
  },
  {
    id: 61,
    nombre: 'Serbia',
    archivo: 'SERBIA.png',
    posX: 1224,
    posY: 837,
    continente: 6,
    escudo: 5,
  },
  {
    id: 62,
    nombre: 'Siberia',
    archivo: 'SIBERIA.png',
    posX: 1162,
    posY: 32,
    continente: 5,
    escudo: 5,
  },
  {
    id: 63,
    nombre: 'Sudafrica',
    archivo: 'SUDAFRICA.png',
    posX: 1224,
    posY: 837,
    continente: 1,
    escudo: 5,
  },
  {
    id: 64,
    nombre: 'Sumatra',
    archivo: 'SUMATRA.png',
    posX: 1212,
    posY: 770,
    continente: 7,
    escudo: 5,
  },
  {
    id: 65,
    nombre: 'Tasmania',
    archivo: 'TASMANIA.png',
    posX: 1343,
    posY: 1037,
    continente: 7,
    escudo: 5,
  },
  {
    id: 66,
    nombre: 'Terranova',
    archivo: 'TERRANOVA.png',
    posX: 1224,
    posY: 837,
    continente: 3,
    escudo: 5,
  },
  {
    id: 67,
    nombre: 'Tonga',
    archivo: 'TONGA.png',
    posX: 1486,
    posY: 799,
    continente: 7,
    escudo: 5,
  },
  {
    id: 68,
    nombre: 'Turquia',
    archivo: 'TURQUIA.png',
    posX: 1165,
    posY: 468,
    continente: 5,
    escudo: 5,
  },
  {
    id: 69,
    nombre: 'Polonia',
    archivo: 'POLONIA.png',
    posX: 1224,
    posY: 837,
    continente: 6,
    escudo: 5,
  },
  {
    id: 70,
    nombre: 'Uruguay',
    archivo: 'URUGUAY.png',
    posX: 362,
    posY: 985,
    continente: 4,
    escudo: 5,
  },
  {
    id: 71,
    nombre: 'Venezuela',
    archivo: 'VENEZUELA.png',
    posX: 344,
    posY: 715,
    continente: 4,
    escudo: 5,
  },
  {
    id: 72,
    nombre: 'Vietnam',
    archivo: 'VIETNAM.png',
    posX: 1342,
    posY: 529,
    continente: 5,
    escudo: 5,
  }
])


db.limites.insert([
  //paises sudamerica
  { pais1: 6, pais2: 19 },
  { pais1: 6, pais2: 70 },
  { pais1: 6, pais2: 10 },
  { pais1: 6, pais2: 56 },
  { pais1: 6, pais2: 9 },
  { pais1: 9, pais2: 56 },
  { pais1: 9, pais2: 19 },
  { pais1: 9, pais2: 10 },
  { pais1: 10, pais2: 70 },
  { pais1: 10, pais2: 56 },
  { pais1: 10, pais2: 71 },
  { pais1: 10, pais2: 13 },
  { pais1: 10, pais2: 19 },
  { pais1: 13, pais2: 71 },
  { pais1: 13, pais2: 19 },

  //paises america central
  { pais1: 16, pais2: 40 },
  { pais1: 16, pais2: 32 },
  { pais1: 16, pais2: 49 },
  { pais1: 25, pais2: 50 },
  { pais1: 25, pais2: 32 },
  { pais1: 32, pais2: 49 },
  { pais1: 40, pais2: 50 },

  //paises oceania
  { pais1: 7, pais2: 67 },
  { pais1: 7, pais2: 27 },
  { pais1: 7, pais2: 64 },
  { pais1: 7, pais2: 65 },
  { pais1: 27, pais2: 67 },
  { pais1: 54, pais2: 65 },

  //paises Africa
  { pais1: 24, pais2: 60 },
  { pais1: 23, pais2: 60 },
  { pais1: 51, pais2: 60 },
  { pais1: 24, pais2: 23 },
  { pais1: 23, pais2: 51 },
  { pais1: 23, pais2: 4 },
  { pais1: 51, pais2: 48 },
  { pais1: 51, pais2: 63 },
  { pais1: 4, pais2: 48 },
  { pais1: 48, pais2: 63 },
  { pais1: 46, pais2: 63 },
  { pais1: 46, pais2: 24 },
  { pais1: 46, pais2: 48 },

  //paises norteamerica
  { pais1: 11, pais2: 45 },
  { pais1: 11, pais2: 43 },
  { pais1: 45, pais2: 43 },
  { pais1: 45, pais2: 18 },
  { pais1: 45, pais2: 55 },
  { pais1: 55, pais2: 18 },
  { pais1: 55, pais2: 66 },
  { pais1: 55, pais2: 12 },
  { pais1: 12, pais2: 1 },
  { pais1: 12, pais2: 36 },
  { pais1: 12, pais2: 66 },
  { pais1: 66, pais2: 18 },
  { pais1: 66, pais2: 44 },
  { pais1: 18, pais2: 53 },
  { pais1: 53, pais2: 31 },
  { pais1: 31, pais2: 44 },
  { pais1: 31, pais2: 37 },

  // paises Asia
  { pais1: 21, pais2: 42 },
  { pais1: 21, pais2: 20 },
  { pais1: 42, pais2: 41 },
  { pais1: 42, pais2: 14 },
  { pais1: 41, pais2: 14 },
  { pais1: 14, pais2: 72 },
  { pais1: 72, pais2: 33 },
  { pais1: 42, pais2: 20 },
  { pais1: 21, pais2: 20 },
  { pais1: 33, pais2: 20 },
  { pais1: 62, pais2: 20 },
  { pais1: 17, pais2: 20 },
  { pais1: 59, pais2: 20 },
  { pais1: 68, pais2: 20 },
  { pais1: 62, pais2: 17 },
  { pais1: 62, pais2: 59 },
  { pais1: 17, pais2: 59 },
  { pais1: 59, pais2: 68 },
  { pais1: 59, pais2: 35 },
  { pais1: 68, pais2: 35 },
  { pais1: 68, pais2: 35 },
  { pais1: 32, pais2: 33 },
  { pais1: 32, pais2: 68 },
  { pais1: 32, pais2: 38 },
  { pais1: 68, pais2: 38 },
  { pais1: 5, pais2: 38 },
  { pais1: 47, pais2: 20 },
  { pais1: 47, pais2: 14 },
  { pais1: 47, pais2: 72 },
  { pais1: 47, pais2: 33 },

  // paises Europa
  { pais1: 36, pais2: 22 },
  { pais1: 36, pais2: 52 },
  { pais1: 52, pais2: 28 },
  { pais1: 28, pais2: 8 },
  { pais1: 30, pais2: 22 },
  { pais1: 30, pais2: 58 },
  { pais1: 30, pais2: 3 },
  { pais1: 26, pais2: 58 },
  { pais1: 26, pais2: 29 },
  { pais1: 3, pais2: 29 },
  { pais1: 39, pais2: 29 },
  { pais1: 39, pais2: 3 },
  { pais1: 8, pais2: 57 },
  { pais1: 8, pais2: 69 },
  { pais1: 57, pais2: 69 },
  { pais1: 57, pais2: 2 },
  { pais1: 2, pais2: 69 },
  { pais1: 3, pais2: 57 },
  { pais1: 61, pais2: 57 },
  { pais1: 3, pais2: 61 },
  { pais1: 3, pais2: 15 },
  { pais1: 61, pais2: 15 },
  { pais1: 15, pais2: 57 },

  //intercontinentales 
  { pais1: 1, pais2: 21 },
  { pais1: 1, pais2: 42 },
  { pais1: 31, pais2: 36 },
  { pais1: 11, pais2: 67 },
  { pais1: 43, pais2: 16 },
  { pais1: 13, pais2: 50 },
  { pais1: 19, pais2: 7 },
  { pais1: 10, pais2: 60 },
  { pais1: 70, pais2: 51 },
  { pais1: 60, pais2: 26 },
  { pais1: 24, pais2: 69 },
  { pais1: 24, pais2: 34 },
  { pais1: 24, pais2: 38 },
  { pais1: 64, pais2: 33 },
  { pais1: 27, pais2: 72 },
  { pais1: 2, pais2: 34 },
  { pais1: 57, pais2: 35 },
  { pais1: 57, pais2: 59 },
])

db.cartaglobales.insert([
  { tipo: "Combate clásico", cantidad: 20 },
  { tipo: "Nieve", defensa: 1, cantidad: 4 },
  { tipo: "Viento a favor", ataque: 1, cantidad: 4 },
  { tipo: "Fronteras abiertas", fronteraAbierta: true, cantidad: 4 },
  { tipo: "Fronteras cerradas", fronteraCerrada: true, cantidad: 4 },
  { tipo: "Crisis", crisis: true, cantidad: 4 },
  { tipo: "Refuerzos extra", refuerzosExtra: true, cantidad: 4 },
  { tipo: "Descanso Azul", color: "AZUL", cantidad: 1 },
  { tipo: "Descanso Rojo", color: "ROJO", cantidad: 1 },
  { tipo: "Descanso Celeste", color: "CELESTE", cantidad: 1 },
  { tipo: "Descanso Naranja", color: "NARANJA", cantidad: 1 },
  { tipo: "Descanso Verde", color: "VERDE", cantidad: 1 },
  { tipo: "Descanso Amarillo", color: "AMARILLO", cantidad: 1 }
])

db.continentes.insert([
  {
    id: 1,
    nombre: "Africa",
    fichas: 4,
    escudo: "Soldado ancla",
  },
  {
    id: 2,
    nombre: "America Central",
    fichas: 3,
    escudo: "Avión",
  },
  {
    id: 3,
    nombre: "America del Norte",
    fichas: 6,
    escudo: "Super Tarjeta",
  },
  {
    id: 4,
    nombre: "America del Sur",
    fichas: 4,
    escudo: "Avion ancla",
  },
  {
    id: 5,
    nombre: "Asia",
    fichas: 8,
    escudo: "Super tarjeta",
  },
  {
    id: 6,
    nombre: "Europa",
    fichas: 8,
    escudo: "Super tarjeta",
  },
  {
    id: 7,
    nombre: "Oceania",
    fichas: 3,
    escudo: "Soldado",
  },
])

db.escudos.insert([
  { id: 1, tipo: "Avión", valor: [1] },
  { id: 2, tipo: "Soldado", valor: [2] },
  { id: 3, tipo: "Ancla", valor: [4] },
  { id: 4, tipo: "Armas", valor: [1, 2, 4] },
  { id: 5, tipo: "Super tarjeta", valor: [7],},
  { id: 6, tipo: "Avión ancla", valor: [5],},
  { id: 7, tipo: "Soldado ancla", valor: [6],}
])

db.objetivos.insert([
  {
    id: 1,
    nombre: "Ocupar Europa y America del Sur",
  },
  {
    id: 2,
    nombre: "Ocupar America del Norte y Oceania",
  },
  {
    id: 3,
    nombre: "Ocupar Asia y America del Central",
  },
  {
    id: 4,
    nombre: "Ocupar America del Norte, 8 de Asia y 4 de Europa",
  },
  {
    id: 5,
    nombre: "Ocupar 4 de America del Norte, 4 de Europa, 4 de Asia, 3 de Africa, 3 de America del Sur, 3 de America Central y 3 de Oceania",
  }
])
